"""Fix nullable for related_request_id

Revision ID: 031a8506720a
Revises: cf09eb8815a8
Create Date: 2025-11-28 00:52:26.914927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031a8506720a'
down_revision: Union[str, None] = 'cf09eb8815a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
