"""코멘트 작성

Revision ID: 642ba19fa669
Revises: 4c5db9b0f4d2
Create Date: 2025-12-11 14:37:20.113504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '642ba19fa669'
down_revision: Union[str, None] = '4c5db9b0f4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fcm_tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('fcm_token'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    op.alter_column('notifications', 'type',
               existing_type=mysql.ENUM('REQUEST', 'ACTIVITY_START', 'ACTIVITY_END', 'PHOTO_UPLOAD', 'PET_UPDATE', 'SYSTEM_RANKING', 'SYSTEM_WEATHER', 'SYSTEM_REMINDER', 'SYSTEM_HEALTH', 'SOS', 'SOS_RESOLVED'),
               type_=sa.Enum('REQUEST', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'ACTIVITY_START', 'FAMILY_ROLE_CHANGED', 'ACTIVITY_END', 'PET_UPDATE', 'SYSTEM_RANKING', 'SYSTEM_WEATHER', 'SYSTEM_HEALTH', 'PET_MEMBER_LEFT', name='notificationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('REQUEST', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'ACTIVITY_START', 'FAMILY_ROLE_CHANGED', 'ACTIVITY_END', 'PET_UPDATE', 'SYSTEM_RANKING', 'SYSTEM_WEATHER', 'SYSTEM_HEALTH', 'PET_MEMBER_LEFT', name='notificationtype'),
               type_=mysql.ENUM('REQUEST', 'ACTIVITY_START', 'ACTIVITY_END', 'PHOTO_UPLOAD', 'PET_UPDATE', 'SYSTEM_RANKING', 'SYSTEM_WEATHER', 'SYSTEM_REMINDER', 'SYSTEM_HEALTH', 'SOS', 'SOS_RESOLVED'),
               existing_nullable=False)
    op.drop_table('user_fcm_tokens')
    # ### end Alembic commands ###
