"""init

Revision ID: a29cab4a8b6b
Revises: 
Create Date: 2025-11-19 06:21:09.469390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29cab4a8b6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('family_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('sns', sa.Enum('google', 'apple', 'kakao', 'email', name='sns_enum'), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_img_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('family_members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='memberrole'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('pet_search_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', 'Unknown', name='petgender'), nullable=True),
    sa.Column('disease', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pet_id'),
    sa.UniqueConstraint('pet_search_id')
    )
    op.create_table('activity_stats',
    sa.Column('stats_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_walks', sa.Integer(), nullable=True),
    sa.Column('total_distance_km', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('total_duration_min', sa.Integer(), nullable=True),
    sa.Column('avg_speed_kmh', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('calories_burned', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.PrimaryKeyConstraint('stats_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('REQUEST', 'ACTIVITY_START', 'ACTIVITY_END', 'PHOTO_UPLOAD', 'PET_UPDATE', 'SYSTEM_RANKING', 'SYSTEM_WEATHER', 'SYSTEM_REMINDER', 'SYSTEM_HEALTH', 'SOS', 'SOS_RESOLVED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('related_pet_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_lat', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('related_lng', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], ),
    sa.ForeignKeyConstraint(['related_pet_id'], ['pets.pet_id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('pet_share_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('pet_walk_goals',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('target_walks', sa.Integer(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('target_distance_km', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.PrimaryKeyConstraint('goal_id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('pet_walk_recommendations',
    sa.Column('rec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('min_walks', sa.Integer(), nullable=False),
    sa.Column('min_minutes', sa.Integer(), nullable=False),
    sa.Column('min_distance_km', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('recommended_walks', sa.Integer(), nullable=False),
    sa.Column('recommended_minutes', sa.Integer(), nullable=False),
    sa.Column('recommended_distance_km', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_walks', sa.Integer(), nullable=False),
    sa.Column('max_minutes', sa.Integer(), nullable=False),
    sa.Column('max_distance_km', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.PrimaryKeyConstraint('rec_id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('walks',
    sa.Column('walk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('calories', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('weather_status', sa.String(length=50), nullable=True),
    sa.Column('weather_temp_c', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('walk_id')
    )
    op.create_table('photos',
    sa.Column('photo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.walk_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('walk_tracking_points',
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.walk_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walk_tracking_points')
    op.drop_table('photos')
    op.drop_table('walks')
    op.drop_table('pet_walk_recommendations')
    op.drop_table('pet_walk_goals')
    op.drop_table('pet_share_requests')
    op.drop_table('notifications')
    op.drop_table('activity_stats')
    op.drop_table('pets')
    op.drop_table('family_members')
    op.drop_table('users')
    op.drop_table('families')
    # ### end Alembic commands ###
