"""코멘트 작성

Revision ID: ac5ec9f45c08
Revises: add_voice_url_pets
Create Date: 2025-12-11 03:48:04.475436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5ec9f45c08'
down_revision: Union[str, None] = 'add_voice_url_pets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
