"""change weight to float

Revision ID: b0b4ce5b5925
Revises: d1168f795255
Create Date: 2025-11-15 04:25:52.679402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0b4ce5b5925'
down_revision: Union[str, None] = 'd1168f795255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'weight',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'weight',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=4, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
