"""코멘트 작성

Revision ID: cc21dfa763fc
Revises: 1b6d9e2e2ab8
Create Date: 2025-12-11 13:58:49.946175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc21dfa763fc'
down_revision: Union[str, None] = '1b6d9e2e2ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
