"""Fix MemberRole enum

Revision ID: d2edb277ce13
Revises: a29cab4a8b6b
Create Date: 2025-11-19 06:34:35.865025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd2edb277ce13'
down_revision: Union[str, None] = 'a29cab4a8b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_members', 'role',
               existing_type=mysql.ENUM('OWNER', 'MEMBER'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_members', 'role',
               existing_type=mysql.ENUM('OWNER', 'MEMBER'),
               nullable=True)
    # ### end Alembic commands ###
