"""create notification_reads table

Revision ID: d3c0e73f0a88
Revises: 75a9d7c07d45
Create Date: 2025-11-23 03:40:03.228542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c0e73f0a88'
down_revision: Union[str, None] = '75a9d7c07d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
