"""change walk numeric columns to float

Revision ID: d8cae66f3557
Revises: e6922229ef1b
Create Date: 2025-11-26 06:50:54.702679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8cae66f3557'
down_revision: Union[str, None] = 'e6922229ef1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_stats', 'total_distance_km',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('activity_stats', 'avg_speed_kmh',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('activity_stats', 'calories_burned',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('walks', 'distance_km',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('walks', 'calories',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('walks', 'weather_temp_c',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('walks', 'weather_temp_c',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=4, scale=1),
               existing_nullable=True)
    op.alter_column('walks', 'calories',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('walks', 'distance_km',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('activity_stats', 'calories_burned',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('activity_stats', 'avg_speed_kmh',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('activity_stats', 'total_distance_km',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
